<?php

include(__DIR__."/config.php");

// querystring link - return the url of the file with a hash in the querystring
function qs_link($file_with_path)
{
    if (!file_exists(processing_dir.$file_with_path))
    {
        throw new Exception("file $file_with_path not found");
    }
    $hash = hash_file("sha256", processing_dir.$file_with_path); // hex
    $hash = urlsafe_b64encode($hash); // base 64
    $hash = substr($hash, 0, 6); // first 6 characters only
    // note that $hash would be different if generated by python's
    // urlsafe_b64encode(), but this does not matter. we just want a consistent
    // hash, and we are not using python in this project.
    return "https://".domain."$file_with_path?hash=$hash";
}

function urlsafe_b64encode($data)
{
    return strtr(base64_encode($data), '+/', '-_');
}

function ld_json($file, $name)
{
    $ld_json = array
    (
        "@context" => "http://schema.org",
        "@type" => "WebSite",
        "datePublished" => date("Y-m-d"),
        "description" => site_description,
        "image" => qs_link("/image/shattered-glass-matrix.png"),
        "inLanguage" => "English",
        "name" => $name,
        "url" => "https://".domain."/$file"
    );
    return json_encode($ld_json);
}

?>
